FROM node:20-slim

# Crear directorio de la app
WORKDIR /app

# Copiar package.json e instalar dependencias
COPY package*.json ./
RUN npm install

# Copiar el resto del código
COPY . .

# Exponer puerto 
EXPOSE 3000

CMD ["npm", "run","dev"]
