# Etapa 1: usar Node como base
FROM node:20-slim

# Crear directorio de trabajo dentro del contenedor
WORKDIR /app

# Copiar package.json e instalar dependencias
COPY package*.json ./
RUN npm install && npm install -g npm@latest

# Copiar el resto del código fuente
COPY . .

# Exponer el puerto de la API/Socket.io
EXPOSE 4000

# Comando de inicio
CMD ["npm", "run","dev"]
