"""initial_schema

Revision ID: 43e1da489a33
Revises: 0af4b1d3933b
Create Date: 2026-04-11 18:52:20.545432

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = '43e1da489a33'
down_revision: Union[str, None] = '0af4b1d3933b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
